### ISSUE TITLE
core-2021.5.0b1 and alarmo

### ISSUE THREAD

**Issue by martkotur** [nielsfaber/alarmo#190]
Alarmo master don't work with core-2021.5.0b1

Logger: homeassistant.config_entries
Source: custom_components/alarmo/card.py:37
Integration: Alarmo (documentation, issues)
First occurred: 9:47:47 (1 occurrences)
Last logged: 9:47:47

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alarmo/__init__.py", line 77, in async_setup_entry
    await async_register_card(hass)
  File "/config/custom_components/alarmo/card.py", line 37, in async_register_card
    hass.data[DATA_EXTRA_MODULE_URL].update(url_set)
AttributeError: 'UrlManager' object has no attribute 'update'

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:52:16 (6 occurrences)
Last logged: 10:04:53
[547458051280] Received invalid command: alarmo/users

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/alarmo/issues/186
