### ISSUE TITLE
Alarmo Failed after 2023.7 update

### ISSUE THREAD

**Issue by theyapps** [nielsfaber/alarmo#760]
### Alarmo Version

1.9.9

### HA Version

2023.7.1

### Bug description

After updating to 2029.7.1 Alarmo fails to start. 

![image](https://github.com/nielsfaber/alarmo/assets/15441/022666d3-d67d-406e-9af9-567c97027548)

### Steps to reproduce

update to 2029.7.1

### Relevant log output

```shell
Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alarmo/__init__.py", line 39, in <module>
    from .automations import AutomationHandler
  File "/config/custom_components/alarmo/automations.py", line 5, in <module>
    from homeassistant.core import (
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
```

**Comment by wesleykirkland** [comment]
I'm having this issue to. I saw in the release notes that they redid services as a whole and I'm expecting that to be the underlying root cause of the module import failure.

https://www.home-assistant.io/blog/2023/07/05/release-20237/

**Comment by wesleykirkland** [comment]
Go into HACS and update Alarmo.

1.9.10 was released which explicitly mentions the deprecation.

https://github.com/nielsfaber/alarmo/commit/fe9981744ee4915b35b1f1d2d64e5ea025172063

See the release here https://github.com/nielsfaber/alarmo/releases/tag/v1.9.10

**Comment by theyapps** [comment]
Oh whoops my bad I forgot that alarmo is updated in HACS
