### ISSUE TITLE
Alarmo integration not loading

### ISSUE THREAD

**Issue by Smurf634** [nielsfaber/alarmo#718]
### Alarmo Version

1.8.1

### HA Version

2023.5.1

### Bug description

The alarmo integration doesn't load in the new HA update

### Steps to reproduce

None.
The integration just doesn't load

**Comment by nielsfaber** [comment]
I am running on HA 2023.5 as well, no issues here.
I suggest to check the HA logs for more details.
If you see ‘loading’ in the alarmo panel you should clear the browser cache.

**Comment by Smurf634** [comment]
I deleted alarmo and reinstalled it.
HA doesn't load alarmo because it is not a tested integration

**Comment by Danieldanielsp** [comment]
Same problem here.

**Comment by Danieldanielsp** [comment]
2023-05-06 08:03:02.397 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-06 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alarmo for alarmo
File "/config/custom_components/alarmo/__init__.py", line 51, in async_setup_entry

**Comment by MihaiP17** [comment]
I had similar problem after updating home assistant to 2023.5.2. I had the following error in the log:

`2023-05-06 19:35:12.704 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 51, in async_setup_entry
    device_registry = await dr.async_get_registry(hass)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get_registry'`

How I managed to fix it:
  - Noticed that Alarmo was no longer present in HACS, in Integrations.
  - Pres + button and search for the integration.
  - Download integration.
  - Restart Home Assistant.

Now everything is back in place.

**Comment by Danieldanielsp** [comment]
> How I managed to fix it:
> 
> * Noticed that Alarmo was no longer present in HACS, in Integrations.
> * Pres + button and search for the integration.
> * Download integration.
> * Restart Home Assistant.
> 
> Now everything is back in place.

this solved it for me. Thank you @MihaiP17  for your help and @nielsfaber for the great software!

**Comment by robertfgoodworth** [comment]
Please help,  This is my first attempt to use Alarmo, love the idea, sadly this did not work for me, it's a brand new deployment.  My HA is the latest with zero update pending. It seemed to of download ok via HACS. I then found it in intergrations and said yes to deploy, then it showed up in Intergrations with a redbox with"error", was so disapointed to see that happen.  I checked the known issues and althrough simular I could not find an existing issue as mine according to the logs.

LOG:
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/alarmo/store.py:674
Integration: Alarmo (documentation, issues)
First occurred: 9:40:50 AM (3 occurrences)
Last logged: 4:38:46 PM

Error setting up entry Alarmo for alarmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/alarmo/__init__.py", line 55, in async_setup_entry
    store = await async_get_registry(hass)
  File "/config/custom_components/alarmo/store.py", line 674, in async_get_registry
    return cast(AlarmoStorage, await task)
TypeError: SensorEntry.__init__() got an unexpected keyword argument 'entity'
#####

Please help, i'd so like to use this for my HA Alarm needs, looks so impressive.
Regards
Rob

**Comment by nielsfaber** [comment]
@robertfgoodworth Could you create a separate bug report for this?
Please mention the versions of HA and alarmo you are using, then I could check if I can reproduce & tackle this.

**Comment by nielsfaber** [comment]
@Smurf634 Do you still experience issues? If so, could you tell what step fails for you?

**Comment by Smurf634** [comment]
I had gondeletentje integration and delete it in HACS.
Then i was able tondow load it again in HACS. Installed the integration and everything worked again.

Sorry that i didn't reply sooner

**Comment by eugeneniemand** [comment]
@nielsfaber I'm on 2023.4.6 and V1.9.9. I've been using this for a very long time, and went to make a change today and only got the loading... message. This happened on all devices, wall tablet, phone and PC. I went to HACS to see if there is an update only to find that I cant find Alarmo at all, even though it was installed and working apart from UI Loading... issue. I clicked add in HACS and it gave me the option to install 1.9.9 which I did and can now see it in HACS again. I can see it in the side bar and I can arm/disarm etc but still get loading message. I have tried Chrome, Brave and Edge and cleared cache and cookies and still face the same issue. I had a look in the logs and the normal HACS message about custom integrations does appear for Alarmo. I spotted a message where it mentioned Alarmo updated storage from 2.1 to 6.1 so not sure if there is something in my config which is not valid. I'm going away tomorrow and dont want to break anything or delete and re-install it. Any ideas?

**Comment by nielsfaber** [comment]
@eugeneniemand 
Alarmo v1.9.9 is the latest version so if it is installed that should solve the ‘loading’ issue.
If the issue is still there, this is due to browser caching problems. Many users experienced this as well. You will have to clear the cache yourself.

If the storage was updated from version 2 to 6 this suggests that you haven’t made any change in alarmo in almost 2 years. That shouldn’t be an issue but obviously I did not test for that so that will be at your own risk. My tests assume incremental updates so e.g. from 5 to 6.

Regardless of the caching issue you should be able to use the alarm as normal. The issue only  affects access to the configuration panel.

**Comment by eugeneniemand** [comment]
That's ok for now thanks. I used the dev tools to clear home assistant cache and cookies as well as in settings removed data stored by my home assistant instance. Any other way to clear cache? Not sure why this would happen across all devices including in browsers that has never accessed HA before. 

Is there a way I can backup/reference my existing configuration so I can try reinstall it and then restore the configuration or at least reference it as I can't remember all the settings I had?
