### ISSUE TITLE
Doesnt work after Upgrade to 2023.7

### ISSUE THREAD

**Issue by alexpthe1** [nielsfaber/alarmo#767]
### Alarmo Version

v1

### HA Version

2023.7

### Bug description

After Upgrading to 2023.7 this Integration does not work anymore

Recieving Error:

2023-07-13 20:46:49.950 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-13 20:47:08.352 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
File "/config/custom_components/alarmo/__init__.py", line 39, in <module>
File "/config/custom_components/alarmo/automations.py", line 5, in <module>

### Steps to reproduce

Update to 2023.7 with installed Alarmo

### Relevant log output

```shell
2023-07-13 20:46:49.950 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-13 20:47:08.352 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
File "/config/custom_components/alarmo/__init__.py", line 39, in <module>
File "/config/custom_components/alarmo/automations.py", line 5, in <module>
```

**Comment by nielsfaber** [comment]
Duplicate issue

**Comment by jeffdoubleyou** [comment]
Duplicate of what?  How do we fix this?
