### ISSUE TITLE
 cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core'  

### ISSUE THREAD

**Issue by charles-xuereb** [nielsfaber/alarmo#762]
### Alarmo Version

V1.9.9

### HA Version

2023.7.0

### Bug description

Immediacy after update to 2023.7.0 the integration failed.

### Steps to reproduce

Install 2023.7.0

### Relevant log output

```shell
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/alarmo/automations.py:5
Integration: Alarmo (documentation, issues)
First occurred: 9:10:16 AM (1 occurrences)
Last logged: 9:10:16 AM

Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
component = integration.get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/config/custom_components/alarmo/init.py", line 39, in
from .automations import AutomationHandler
File "/config/custom_components/alarmo/automations.py", line 5, in
from homeassistant.core import (
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
```

**Comment by nielsfaber** [comment]
Use latest alarmo version.

**Comment by charles-xuereb** [comment]
Thanks for you help and a great customer integration.
Cheers

**Comment by Akhundoff** [comment]
> Thanks for you help and a great customer integration. Cheers

How did you solve this? Have you uninstalled and reinstalled Alarmo?

**Comment by nielsfaber** [comment]
@Akhundoff Update your alarmo version via HACS
