### ISSUE TITLE
Can't arm area through MQTT

### ISSUE THREAD

**Issue by mreiling** [nielsfaber/alarmo#102]
This could very well be user error.  I have two areas set up (house & garage).  When sending the command to the command topic, I get an error that area was not defined.  Just for giggles I tried to define an area in JSON (but my alarm app/panel doesn't support this anyway) and got this error:

2021-01-21 08:06:17 DEBUG (MainThread) [custom_components.alarmo.mqtt] DISARM
2021-01-21 08:06:17 DEBUG (MainThread) [custom_components.alarmo.mqtt] Received command disarm
2021-01-21 08:06:17 ERROR (MainThread) [homeassistant.util.logging] Exception in async_message_received when handling msg on 'alarm/set': '{
  "command": "DISARM",
  "area": "house"
}'
Traceback (most recent call last):
  File "/config/custom_components/alarmo/mqtt.py", line 175, in async_message_received
    await entity.async_alarm_disarm(code, skip_code)
AttributeError: 'filter' object has no attribute 'async_alarm_disarm'

Would it be possible to define the MQTT commands and states in the areas?  Or perhaps just automatically add a listener similar to how you add the state publishing?

**Comment by nielsfaber** [comment]
Hello,
I must say that the mqtt implementation is still in the works.
It should be possible to arm a dedicated area using the method you use, but apparently it doesn’t work out of the box yet.
I will try to test this in the coming days.
 
> Would it be possible to define the MQTT commands and states in the areas? Or perhaps just automatically add a listener similar to how you add the state publishing?

These are the kind of questions I have been asking myself as well.
I recommend users to enable the “master alarm” and use that for arming/disarming.
But ofcourse the user should have the freedom to interface with areas directly.

A problem is that the MQTT configuration panel has a lot of settings (due to customizable payloads), I don’t think it’s wise (or needed) to have this setup for each area.
Would you prefer to see dedicated state+command topics per area, or would the addition of a JSON “area” parameter be sufficient?

Note that I’m planning to expand mqtt functionality, for example by reporting diagnostically information (like wrong password or open sensors list), but also adding a command out + state in topic, such that a remote alarm panel can be kept in sync.
I’m afraid these additions together with the area customizations, will result in a complicated procedure.
How would you like to see this?

**Comment by mreiling** [comment]
I think leaving the payload customization in the global settings is fine.  It is likely that someone using MQTT to command the alarm system is likely to use the same solution in every zone.  Perhaps just moving the command and state topics to the zone is the solution?  Or something like this in global:  Alarm State: /alarm/{zone}/state where zone is substituted from the list of zones when creating listeners, etc.  JSON is cool, but not every app support sending JSON payloads.

I myself use the wonderful MQTT Alarm Panel for Android app from ThanksMister.

**Comment by mreiling** [comment]
Also willing to help out if you want, but I would want to know the direction you wanted to head in before creating a PR.

**Comment by nielsfaber** [comment]
I updated the [documentation](https://github.com/nielsfaber/alarmo#mqtt) on MQTT quite a bit, hoping it makes it more clear how things work (also in combination with multiple areas).

I squashed out a nasty bug that caused your error when trying to arm an area, it should work better after updating to v1.5.0.
As said before, the MQTT implementation deserves more attention, hopefully I can take this up soon.

**Comment by mariomazon** [comment]
On a fresh install, with just one area (the default Alarmo area) and mqtt set to default topics, I've got this when sending a payload with DISARM or another command to /alarmo/command topic. Note: fresh install with this last updates above.

Logger: homeassistant.util.logging
Source: util/logging.py:108
First occurred: 2:53:15 PM (1 occurrences)
Last logged: 2:53:15 PM

Exception in async_message_received when handling msg on 'alarmo/command': 'DISARM' Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 167, in async_message_received entity = self.hass.data[const.DOMAIN]["areas"][0] KeyError: 0

Did the following on line 167:
entity = list(self.hass.data[const.DOMAIN]["areas"].values())


but then, got this:

Exception in async_message_received when handling msg on 'alarmo/command': 'DISARM' Traceback (most recent call last): File "/config/custom_components/alarmo/mqtt.py", line 175, in async_message_received await entity.async_alarm_disarm(code, skip_code) AttributeError: 'list' object has no attribute 'async_alarm_disarm'

**Comment by mariomazon** [comment]
Changing line 167 to
entity = list(self.hass.data[const.DOMAIN]["areas"].values())[0]

Now it's working !

**Comment by nielsfaber** [comment]
Looks like you’re right!
If you want the honors, you could make a PR for it. Else I will make sure it’s covered for the next release.

**Comment by mariomazon** [comment]
Sorry, whats a PR ?

No no no.. No need to honors kkk.. Just tried yesterday to migrate from bwalarm to alarmo and got this error. Today I've searched here and found the new release.

Thank you for your attention !

**Comment by nielsfaber** [comment]
@mariomazon  I updated this bug in the code, thanks for reporting.

**Comment by nielsfaber** [comment]
v1.5.1 includes your fix @mariomazon, thanks again.
This issue can be closed.
