### ISSUE TITLE
SERVICE_CALL_LIMIT , Home Assistant 2023.7

### ISSUE THREAD

**Issue by danielsza** [nielsfaber/alarmo#772]
### Alarmo Version

1.9.9

### HA Version

2023.7

### Bug description

Alarmo Failes to start in 2023.7 -2023.7.2

error is SERVICE_CALL_LIMIT

in automations.py

remove line #8    'SERVICE_CALL_LIMIT,'

add 
 line #11      'SERVICE_CALL_LIMIT = 10'

### Steps to reproduce

upgrade to 2023.7.2

**Comment by abenedet78** [comment]
I have the same issue since upgrading to 2023.7.3. Here is the log:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/alarmo/automations.py:5
Integration: alarmo (documentation, issues)
First occurred: July 24, 2023 at 2:25:07 PM (1 occurrences)
Last logged: July 24, 2023 at 2:25:07 PM

Setup failed for custom integration alarmo: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/alarmo/__init__.py", line 39, in <module>
    from .automations import AutomationHandler
  File "/config/custom_components/alarmo/automations.py", line 5, in <module>
    from homeassistant.core import (
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
